matrix:
  allow_failures:
    - env: CABALVER=head GHCVER=head
    - env: CABALVER=1.22 GHCVER=7.10.1
    - env: HPVER=2013.2.0.0

env:
 - CABALVER=1.18 GHCVER=7.6.3
 - CABALVER=1.20 GHCVER=7.8.3
 - CABALVER=1.22 GHCVER=7.10.1
 - CABALVER=head GHCVER=head
 - HPVER=2013.2.0.0

before_install:
 - case "$HPVER" in
    "") touch cabal.config ;;

    "2013.2.0.0")
      export GHCVER=7.6.3 ;
      export CABALVER=1.18 ;
      echo "constraints:async==2.0.1.4,attoparsec==0.10.4.0,case-insensitive==1.0.0.1,cgi==3001.1.7.5,fgl==5.4.2.4,GLUT==2.4.0.0,GLURaw==1.3.0.0,haskell-src==1.0.1.5,hashable==1.1.2.5,html==1.0.1.2,HTTP==4000.2.8,HUnit==1.2.5.2,mtl==2.1.2,network==2.4.1.2,OpenGL==2.8.0.0,OpenGLRaw==1.3.0.0,parallel==3.2.0.3,parsec==3.1.3,QuickCheck==2.6,random==1.0.1.1,regex-base==0.93.2,regex-compat==0.95.1,regex-posix==0.95.2,split==0.2.2,stm==2.4.2,syb==0.4.0,text==0.11.3.1,transformers==0.3.0.0,unordered-containers==0.2.3.0,vector==0.10.0.1,xhtml==3000.2.1,zlib==0.5.4.1" > cabal.config ;;

    *)
      export GHCVER=unknown ;
      echo "unknown/invalid Haskell Platform requested" ;
      touch cabal.config;
      exit 1 ;;

   esac

 - cp cabal.config yi
 - sudo add-apt-repository -y ppa:hvr/ghc
 - sudo apt-get update
 - sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER libicu-dev
 - export PATH=/opt/ghc/$GHCVER/bin:$PATH

install:
 - cabal-$CABALVER update
 - travis_retry cabal-$CABALVER install Cabal
 - travis_retry sudo apt-get install happy-1.19.4 alex-3.1.3
 - export PATH=/opt/alex/3.1.3/bin:/opt/happy/1.19.4/bin:$PATH
 - travis_retry cabal-$CABALVER install -j2 gtk2hs-buildtools

script:
 - travis_retry cabal-$CABALVER install -j2 -fpango --enable-tests -ftesting --only-dependencies --reorder-goals --force-reinstalls
 - cabal-$CABALVER install -j1 -fpango --enable-tests -ftesting
 - cabal-$CABALVER test
 # - cd ../yi/example-configs
 # - for config in yi-*.hs;
 #   do
 #     ghc -Wall --make $config;
 #   done;


notifications:
  irc: "chat.freenode.net#yi"
