sudo: false
language: generic

cache:
  directories:
  - $HOME/.stack
  - $HOME/.local/bin

jobs:
  include:
    - stage: "Prepare"
      script: stack setup --stack-yaml=lts-7.yaml
    - script: stack install --stack-yaml=stack.yaml --install-ghc gtk2hs-buildtools
    - stage: "Build and test"
      script: stack --install-ghc --stack-yaml=lts-7.yaml test -j2
    - script: stack --stack-yaml=stack.yaml test -j2
    - script: stack --stack-yaml=stack-ghc-8.2.yaml test --install-ghc
    - stage: "Build example configs"
      script: stack --stack-yaml=all-configs.yaml build -j2

addons:
  apt:
    packages:
    - libgmp-dev
    - alex
    sources: hvr-ghc

before_install:
 - mkdir -p $HOME/.local/bin
 - curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
