matrix:
  allow_failures:
    - env: CABALVER=head GHCVER=head

env:
 - CABALVER=1.20 GHCVER=7.8.4
 - CABALVER=1.22 GHCVER=7.10.3
 - CABALVER=1.24 GHCVER=8.0.1
 - CABALVER=head GHCVER=head

before_install:
 - sudo add-apt-repository -y ppa:hvr/ghc
 - sudo apt-get update
 - sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER libicu-dev
 - export PATH=/opt/ghc/$GHCVER/bin:$PATH

install:
 - cabal-$CABALVER update
 - travis_retry cabal-$CABALVER install Cabal
 - travis_retry sudo apt-get install happy-1.19.4 alex-3.1.3
 - export PATH=/opt/alex/3.1.3/bin:/opt/happy/1.19.4/bin:$PATH
 - travis_retry cabal-$CABALVER install -j2 gtk2hs-buildtools

script:
 - travis_retry cabal-$CABALVER install -j2 -fvty -fpango --enable-tests -ftesting --only-dependencies --reorder-goals --force-reinstalls
 - cabal-$CABALVER install -j1 -fvty -fpango --enable-tests -ftesting
 - cabal-$CABALVER test
 - cd ../yi/example-configs
 - for config in yi*.hs;
   do
     ghc -Wall -Werror -ferror-spans --make $config;
   done;


notifications:
  irc: "chat.freenode.net#yi"
