# Use new container infrastructure to enable caching
sudo: false

# Do not choose a language; we provide our own build tools.
language: generic

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack

matrix:
  include:
  - env: RESOLVER="lts-9"
    addons:
      apt:
        packages:
        - libpango1.0-dev
        - libgtk2.0-dev
  - env: RESOLVER="nightly"
  allow_failures:
  - env: RESOLVER="nightly"

before_install:
# Download and unpack the stack executable
- export PATH=$HOME/.local/bin:$PATH
- mkdir -p ~/.local/bin
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
# install dependencies of yi-core separately to safe memory
- stack test yi-core --no-terminal
                     --install-ghc
                     --stack-yaml travis/$RESOLVER.yaml
                     --resolver $RESOLVER
                     --only-dependencies
- stack test --no-terminal
             --install-ghc
             --stack-yaml travis/$RESOLVER.yaml
             --resolver $RESOLVER
             --only-dependencies

script:
- stack --no-terminal --stack-yaml travis/$RESOLVER.yaml --resolver $RESOLVER test
