matrix:
  allow_failures:
    - env: GHCVER=head
    - env: HPVER=2013.2.0.0

env:
 - GHCVER=7.6.3
 - GHCVER=7.8.1
 - GHCVER=7.8.2
 - GHCVER=7.8.3
 - GHCVER=head
 - HPVER=2013.2.0.0

before_install:
 - case "$HPVER" in
    "") touch cabal.config ;;

    "2013.2.0.0")
      export GHCVER=7.6.3 ;
      echo "constraints:async==2.0.1.4,attoparsec==0.10.4.0,case-insensitive==1.0.0.1,cgi==3001.1.7.5,fgl==5.4.2.4,GLUT==2.4.0.0,GLURaw==1.3.0.0,haskell-src==1.0.1.5,hashable==1.1.2.5,html==1.0.1.2,HTTP==4000.2.8,HUnit==1.2.5.2,mtl==2.1.2,network==2.4.1.2,OpenGL==2.8.0.0,OpenGLRaw==1.3.0.0,parallel==3.2.0.3,parsec==3.1.3,QuickCheck==2.6,random==1.0.1.1,regex-base==0.93.2,regex-compat==0.95.1,regex-posix==0.95.2,split==0.2.2,stm==2.4.2,syb==0.4.0,text==0.11.3.1,transformers==0.3.0.0,unordered-containers==0.2.3.0,vector==0.10.0.1,xhtml==3000.2.1,zlib==0.5.4.1" > cabal.config ;;

    *)
      export GHCVER=unknown ;
      echo "unknown/invalid Haskell Platform requested" ;
      touch cabal.config;
      exit 1 ;;

   esac

 - cp cabal.config yi
 - cp cabal.config yi-contrib
 - sudo add-apt-repository -y ppa:hvr/ghc
 - sudo apt-get update
 - sudo apt-get install cabal-install-1.20 ghc-$GHCVER libicu-dev
 - export PATH=/opt/ghc/$GHCVER/bin:$PATH

install:
 - cabal-1.20 update
 - travis_retry cabal-1.20 install Cabal
 - travis_retry cabal-1.20 install -j2 alex happy
 - travis_retry cabal-1.20 install -j2 gtk2hs-buildtools

script:
 - cd yi
 - travis_retry cabal-1.20 install -j2 -fpango --enable-tests -ftesting --only-dependencies --reorder-goals --force-reinstalls --constraint=optparse-applicative==0.10.0
 - cabal-1.20 install -j1 -fpango --enable-tests -ftesting
 - cd ../yi/example-configs
 # - for config in yi-*.hs;
 #   do
 #     ghc -Wall --make $config;
 #   done;

 - cd ../../yi-contrib
 - cabal-1.20 install

notifications:
  irc: "chat.freenode.net#yi"
